version: '2'
services:
  wp:
    build: ./www
    container_name: gutenberg_wp
    volumes:
      - ./www/html/assets:/var/www/html/assets
      - ./data/log/apache:/var/log/apache2
    ports:
      - 80:80
    links:
      - mysql
    environment:
      DOMAIN: gutenberg.test
      APACHE_DOCROOT: /var/www/html
      APACHE_LOG_DIR: /var/log/apache2
      PROJECT_NAME: gutenberg
      WP_DB_HOST: mysql:3306
      WP_DB_NAME: gutenberg
      WP_DB_USER: gutenberg
      WP_DB_PASSWORD: 3030
      CTS_USE_LANG: 1
      CTS_INCLUDE_PATH: /var/www/html/assets/uploads/inc
  mysql:
    image: mysql:5.7.21
    container_name: gutenberg_mysql
    ports:
      - 3306:3306
    working_dir: /sql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/sql:/sql
      - ./data/log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gutenberg
      MYSQL_USER: gutenberg
      MYSQL_PASSWORD: 3030
